name: Trigger auto deployment for container-app-7tugc7okmy3k2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-7tugc7okmy3k2-AutoDeployTrigger-98ef1b79-469a-489a-8d8d-9b1745aaf220.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP7TUGC7OKMY3K2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP7TUGC7OKMY3K2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP7TUGC7OKMY3K2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry7tugc7okmy3k2.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP7TUGC7OKMY3K2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP7TUGC7OKMY3K2_REGISTRY_PASSWORD }}
          containerAppName: container-app-7tugc7okmy3k2
          resourceGroup: expresssample8db98d0f
          imageToBuild: containerregistry7tugc7okmy3k2.azurecr.io/container-app-7tugc7okmy3k2:${{ github.sha }}
          


